<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Grpc.AspNetCore" />
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" />
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
    <PackageReference Include="Scalar.AspNetCore" />
  </ItemGroup>

  <ItemGroup>
    <Protobuf Include="Protos\identity.proto" GrpcServices="Server" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Micron.Identity.Application\Micron.Identity.Application.csproj" />
    <ProjectReference Include="..\Micron.Identity.Persistence\Micron.Identity.Persistence.csproj" />
    <ProjectReference Include="..\Micron.Identity.Infrastructure\Micron.Identity.Infrastructure.csproj" />
  </ItemGroup>

</Project>
